"""
This module provides functions to extract structured information from CVs and job descriptions using Gemini API.

Prerequisites:
- GEMINI_API_KEY must be set in .env file or environment variables
"""
import re
import os
import json
import logging
from dotenv import load_dotenv
import google.generativeai as genai

# --- Gemini Configuration ---

load_dotenv()
try:
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        raise ValueError("GEMINI_API_KEY not found in .env file or environment variables.")
    genai.configure(api_key=api_key)
    genai_model = genai.GenerativeModel('gemini-2.5-flash')
except (ValueError, ImportError) as e:
    print(f"Error: Gemini model could not be configured. Error: {e}")
    genai_model = None

# --- Logger Configuration ---
logger = logging.getLogger(__name__)

# --- Helper Functions ---

def repair_malformed_json(json_str):
    """
    Attempts to repair common JSON syntax errors generated by LLMs.
    Specifically handles arrays incorrectly closed with '}' instead of ']'.
    """
    # Remove all trailing whitespace and fix common JSON issues
    json_str = re.sub(r',\s*}', '}', json_str)  # Remove trailing commas before }
    json_str = re.sub(r',\s*]', ']', json_str)  # Remove trailing commas before ]
    
    # Generic fix: "string" } -> "string" ]
    # This looks for a closing quote, optional whitespace, newline, optional whitespace, closing brace, and optional comma
    json_str = re.sub(r'"\s*\n\s*\}\s*(,?)', r'"\n  ]\1', json_str)
    
    # Specific fix for known list fields if they are closed with }
    # This matches: "field": [ ... } (where ... does not contain ])
    list_fields = [
        "education", "experience", "skills", "academic_projects", "diplomas", 
        "responsibilities", "education_requirements"
    ]
    
    for field in list_fields:
        # Pattern looks for the field start, then content without ']', then a closing '}'
        # We replace the closing '}' with ']'
        pattern = rf'("{field}"\s*:\s*\[[^\]]*?)\}}\s*(,?)'
        json_str = re.sub(pattern, r'\1]\2', json_str, flags=re.DOTALL)
        
    return json_str

# --- Gemini Based Extraction ---

def extract_information_from_cv_gemini(cv_text):
    """
    Extracts structured information from a CV using the Gemini LLM.

    Args:
        cv_text (str): The raw text content of the CV.

    Returns:
        dict: A dictionary containing extracted information.
        
    Raises:
        RuntimeError: If Gemini model is not configured or extraction fails.
    """
    if not genai_model:
        raise RuntimeError(
            "Gemini API is not configured. Please set GEMINI_API_KEY in your .env file. "
            "Get your API key from https://makersuite.google.com/app/apikey"
        )

    prompt = f'''
    You are an expert in CV and resume parsing. Your task is to analyze the provided text and extract key information into a structured JSON format.

    Please extract the following fields:
    - "name": The candidate's full name.
    - "contact": An object containing:
        - "email": The candidate's email address (as a string).
        - "phone": The candidate's phone number (as a string).
    - "education": A list of strings, where each string is an education entry (e.g., "Master in Computer Science, University of Paris (2020 - 2022) (2 years)").
    - "experience": A list of strings, where each string is a professional experience entry.
    - "skills": A list of strings, where each string is a skill.
    - "academic_projects": A list of strings for any academic or personal project mentioned.
    - "diplomas": A list of strings for any diploma or certification mentioned.

    Rules:
    - The entire output must be a single valid JSON object.
    - Do not include any text, explanation, or markdown formatting like ```json before or after the JSON object.
    - If a section or information is not found, use an empty list `[]` for list fields or `null` for string/object fields.
    - Ensure all lists (arrays) are closed with `]` and not `}}`.
    - Clean the extracted text to remove unnecessary newlines or formatting within strings.

    Here is the CV text to analyze:
    ---
    {cv_text}
    ---
    '''

    try:
        response = genai_model.generate_content(prompt)
        
        # Clean the response to get only the JSON part
        response_text = response.text.strip()
        
        # Remove markdown code fences if present (handles ```json and ```)
        if '```' in response_text:
            # Extract content between code fences
            match = re.search(r'```(?:json)?\s*\n(.*?)\n```', response_text, re.DOTALL)
            if match:
                response_text = match.group(1)
            else:
                # Fallback: remove fences line by line
                response_text = re.sub(r'^```(?:json)?\s*\n', '', response_text, flags=re.MULTILINE)
                response_text = re.sub(r'\n```\s*$', '', response_text, flags=re.MULTILINE)
        
        # Strip any remaining whitespace
        cleaned_response = response_text.strip()
        
        # Additional cleaning: remove trailing whitespace from each line
        lines = cleaned_response.split('\n')
        cleaned_lines = [line.rstrip() for line in lines]
        cleaned_response = '\n'.join(cleaned_lines)
        
        # Try to parse the JSON
        extracted_data = json.loads(cleaned_response)
        return extracted_data
    except json.JSONDecodeError as e:
        # Try one more time with aggressive cleaning
        try:
            cleaned = repair_malformed_json(cleaned_response)
            extracted_data = json.loads(cleaned)
            logger.warning("Successfully parsed JSON after aggressive cleaning")
            return extracted_data
        except json.JSONDecodeError:
            error_msg = f"Failed to parse JSON from Gemini response: {e}"
            if 'response' in locals():
                error_msg += f"\n--- Raw Response ---\n{response.text}\n-------------------"
            raise RuntimeError(error_msg)
    except Exception as e:
        error_msg = f"Gemini API error during CV extraction: {str(e)}"
        if 'response' in locals() and hasattr(response, 'text'):
            error_msg += f"\n--- Response Text ---\n{response.text}\n-------------------"
        raise RuntimeError(error_msg)

def extract_information_from_jd_gemini(jd_text):
    """
    Extrait des informations structurées d'une fiche de poste (Job Description) 
    en utilisant le LLM Gemini.

    Args:
        jd_text (str): Le texte brut de la fiche de poste.

    Returns:
        dict: Un dictionnaire contenant les informations extraites.
        
    Raises:
        RuntimeError: If Gemini model is not configured or extraction fails.
    """
    if not genai_model:
        raise RuntimeError(
            "Gemini API is not configured. Please set GEMINI_API_KEY in your .env file. "
            "Get your API key from https://makersuite.google.com/app/apikey"
        )

    prompt = f'''
    You are a recruitment expert and job description analyst. Your task is to analyze the provided job offer text and extract key information into a structured JSON format.

    Please extract the following fields:
    - "job_title": The exact job title (e.g., "Senior Full-Stack Developer").
    - "company_name": The hiring company name (if mentioned).
    - "location": The workplace location (e.g., "Paris, France", "Remote", "Hybrid (Lyon)").
    - "job_type": The contract type (e.g., "Permanent", "Fixed-term", "Internship", "Freelance", "Part-time").
    - "responsibilities": A list of strings, where each string is a key responsibility or duty.
    - "skills": A list of strings, where each string is a skill.
    - "experience_level": A textual description of the required experience level (e.g., "Junior", "Senior", "3-5 years experience", "Beginner accepted").
    - "education_requirements": A list of strings for required degrees or education levels (e.g., "Master's in Computer Science", "Engineering Degree").

    Rules:
    - The entire output must be a single valid JSON object.
    - Do not include any text, explanation, or markdown formatting like ```json before or after the JSON object.
    - If a section or information is not found, use an empty list `[]` for list fields or `null` for string/object fields.
    - Ensure all lists (arrays) are closed with `]` and not `}}`.
    - Clean the extracted text to remove unnecessary newlines or formatting within strings.

    Here is the job description text to analyze:
    ---
    {jd_text}
    ---
    '''

    try:
        response = genai_model.generate_content(prompt)
        
        # Clean the response to get only the JSON part
        response_text = response.text.strip()
        
        # Remove markdown code fences if present (handles ```json and ```)
        if '```' in response_text:
            # Extract content between code fences
            match = re.search(r'```(?:json)?\s*\n(.*?)\n```', response_text, re.DOTALL)
            if match:
                response_text = match.group(1)
            else:
                # Fallback: remove fences line by line
                response_text = re.sub(r'^```(?:json)?\s*\n', '', response_text, flags=re.MULTILINE)
                response_text = re.sub(r'\n```\s*$', '', response_text, flags=re.MULTILINE)
        
        # Strip any remaining whitespace
        cleaned_response = response_text.strip()
        
        # Additional cleaning: remove trailing whitespace from each line
        lines = cleaned_response.split('\n')
        cleaned_lines = [line.rstrip() for line in lines]
        cleaned_response = '\n'.join(cleaned_lines)
        
        # Try to parse the JSON
        extracted_data = json.loads(cleaned_response)
        return extracted_data
    except json.JSONDecodeError as e:
        # Try one more time with aggressive cleaning
        try:
            cleaned = repair_malformed_json(cleaned_response)
            extracted_data = json.loads(cleaned)
            logger.warning("Successfully parsed JSON after aggressive cleaning")
            return extracted_data
        except json.JSONDecodeError:
            error_msg = f"Failed to parse JSON from Gemini response: {e}"
            if 'response' in locals():
                error_msg += f"\n--- Raw Response ---\n{response.text}\n-------------------"
            raise RuntimeError(error_msg)
    except Exception as e:
        error_msg = f"Gemini API error during job description extraction: {str(e)}"
        if 'response' in locals() and hasattr(response, 'text'):
            error_msg += f"\n--- Response Text ---\n{response.text}\n-------------------"
        raise RuntimeError(error_msg)
